feat(git): delete unused alias: `delete-branch-force`
When failing to delete a branch, Git tells an command example to delete forcibly.

E.g.

```
$ git delete-branch foo/bar
error: The branch 'foo/bar' is not fully merged.
If you are sure you want to delete it, run 'git branch -D foo/bar'.
```